-- CreateEnum
CREATE TYPE "STATUS_TASK" AS ENUM ('TODO', 'PROCESS', 'DONE');

-- CreateTable
CREATE TABLE "Notes" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "status" "STATUS_TASK" NOT NULL DEFAULT 'TODO',
    "time" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notes_pkey" PRIMARY KEY ("id")
);
